# Generated by Django 5.2.4 on 2025-08-20 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipeDirigeante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('lienFacebook', models.CharField(max_length=100)),
                ('lienInstagram', models.CharField(max_length=100)),
                ('lienTwitter', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('dateHeure', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='evenements')),
            ],
        ),
        migrations.CreateModel(
            name='TypeEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_type_evenement', models.CharField(max_length=100)),
                ('description_type_evenement', models.TextField()),
                ('image_type_evenement', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='EvenementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='evenements/images')),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='firtsApp.evenement')),
            ],
        ),
        migrations.CreateModel(
            name='Temoingnage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('image', models.ImageField(upload_to='temoignage')),
                ('nom', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='videos/')),
                ('evenement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temoignage', to='firtsApp.evenement')),
            ],
        ),
        migrations.AddField(
            model_name='evenement',
            name='typeEvenement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenement', to='firtsApp.typeevenement'),
        ),
    ]
