# Generated by Django 5.2.4 on 2025-08-20 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firtsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='titre',
        ),
    ]
