# Generated by Django 5.2.4 on 2025-10-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firtsApp', '0002_remove_evenement_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
