# Generated by Django 5.2.4 on 2025-10-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firtsApp', '0004_alter_evenement_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
