# Generated by Django 5.2.4 on 2025-10-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firtsApp', '0005_alter_evenement_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='titre',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
