# Generated by Django 5.2 on 2025-11-10 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firtsApp', '0006_evenement_titre'),
        ('secondApp', '0003_equipedirigeante_typeevenement_evenement_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EquipeDirigeante',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='typeEvenement',
        ),
        migrations.RemoveField(
            model_name='temoingnage',
            name='evenement',
        ),
        migrations.RemoveField(
            model_name='evenementimage',
            name='evenement',
        ),
        migrations.DeleteModel(
            name='TypeEvenement',
        ),
        migrations.DeleteModel(
            name='Temoingnage',
        ),
        migrations.DeleteModel(
            name='Evenement',
        ),
        migrations.DeleteModel(
            name='EvenementImage',
        ),
    ]
