# Generated by Django 5.2 on 2025-11-16 23:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debutAnnee', models.DateField()),
                ('finAnnee', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('est_publie', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='annonces/')),
            ],
        ),
        migrations.CreateModel(
            name='TypeEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_type_evenement', models.CharField(max_length=100)),
                ('description_type_evenement', models.TextField()),
                ('image_type_evenement', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('membreLambda', 'Membre Lambda'), ('membreEquipe', "Membre de l'équipe")], default='membreLambda', max_length=20, verbose_name='Rôle')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='utilisateur_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='utilisateur_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EquipeDirigeante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('lienFacebook', models.CharField(max_length=100)),
                ('lienInstagram', models.CharField(max_length=100)),
                ('lienTwitter', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='equipe')),
                ('utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipeDirigeante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('dateHeure', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='evenements')),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('est_publie', models.BooleanField(default=False)),
                ('annee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evement', to='secondApp.annee')),
                ('typeEvenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenement', to='secondApp.typeevenement')),
            ],
        ),
        migrations.CreateModel(
            name='EvenementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='evenements/images')),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='secondApp.evenement')),
            ],
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('prenom', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Adresse email')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('profession', models.CharField(max_length=50)),
                ('numeroUrgence', models.CharField(blank=True, max_length=20, null=True)),
                ('niveauEtude', models.CharField(blank=True, max_length=20, null=True)),
                ('ecole', models.CharField(blank=True, max_length=20, null=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_modification', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='membres/', verbose_name='Photo de profil')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('ner', models.CharField(blank=True, max_length=20, null=True)),
                ('keri', models.CharField(blank=True, max_length=20, null=True)),
                ('keribour', models.CharField(blank=True, max_length=20, null=True)),
                ('keriBa', models.CharField(blank=True, max_length=20, null=True)),
                ('keribourBa', models.CharField(blank=True, max_length=20, null=True)),
                ('utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membre', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Reinscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('numeroUrgence', models.CharField(blank=True, max_length=20, null=True, verbose_name="Numéro d'urgence")),
                ('ecole', models.CharField(blank=True, max_length=50, null=True)),
                ('niveauEtude', models.CharField(blank=True, max_length=20, null=True, verbose_name="Niveau d'étude")),
                ('filiere', models.CharField(blank=True, max_length=150, null=True)),
                ('adresse', models.CharField(blank=True, max_length=150, null=True)),
                ('date_reinscription', models.DateTimeField(auto_now_add=True)),
                ('photo_annuelle', models.ImageField(blank=True, null=True, upload_to='reinscriptions/%Y/', verbose_name="Photo de l'année")),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reinscriptions', to='secondApp.annee')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reinscriptions', to='secondApp.membre')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('payé', 'Payé'), ('non_payé', 'Non payé'), ('moitié_payé', 'Moitié payé'), ('avance', 'Avance')], max_length=20)),
                ('preuve_paiement', models.FileField(blank=True, null=True, upload_to='paiements/')),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondApp.evenement')),
                ('membre_Reinscris', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secondApp.reinscription')),
            ],
        ),
        migrations.CreateModel(
            name='Temoingnage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('image', models.ImageField(upload_to='temoignage')),
                ('nom', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='videos/')),
                ('evenement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temoignage', to='secondApp.evenement')),
            ],
        ),
        migrations.AddIndex(
            model_name='membre',
            index=models.Index(fields=['nom', 'prenom'], name='secondApp_m_nom_6beb12_idx'),
        ),
        migrations.AddIndex(
            model_name='membre',
            index=models.Index(fields=['email'], name='secondApp_m_email_6d46a6_idx'),
        ),
    ]
