# Generated by Django 5.2.4 on 2025-08-20 00:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firtsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('est_publie', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='annonces/')),
            ],
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('prenom', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Adresse email')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('profession', models.CharField(max_length=50)),
                ('numeroUrgence', models.CharField(blank=True, max_length=20, null=True)),
                ('niveauEtude', models.CharField(blank=True, max_length=20, null=True)),
                ('ecole', models.CharField(blank=True, max_length=20, null=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_modification', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='membres/', verbose_name='Photo de profil')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('ner', models.CharField(blank=True, max_length=20, null=True)),
                ('keri', models.CharField(blank=True, max_length=20, null=True)),
                ('keribour', models.CharField(blank=True, max_length=20, null=True)),
                ('keriBa', models.CharField(blank=True, max_length=20, null=True)),
                ('keribourBa', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['nom', 'prenom'],
                'indexes': [models.Index(fields=['nom', 'prenom'], name='secondApp_m_nom_6beb12_idx'), models.Index(fields=['email'], name='secondApp_m_email_6d46a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('payé', 'Payé'), ('non_payé', 'Non payé'), ('moitié_payé', 'Moitié payé')], default='non_payé', max_length=20)),
                ('preuve_paiement', models.FileField(blank=True, null=True, upload_to='paiements/')),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firtsApp.evenement')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondApp.membre')),
            ],
        ),
    ]
