# Generated by Django 5.2 on 2025-11-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debutAnnee', models.DateField()),
                ('finAnnee', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('payé', 'Payé'), ('non_payé', 'Non payé'), ('moitié_payé', 'Moitié payé'), ('avance', 'Avance')], max_length=20),
        ),
    ]
