# Generated by Django 5.2 on 2025-11-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reinscription',
            name='ecole',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='reinscription',
            name='niveauEtude',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Niveau d'étude"),
        ),
        migrations.AlterField(
            model_name='reinscription',
            name='numeroUrgence',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Numéro d'urgence"),
        ),
        migrations.AlterField(
            model_name='reinscription',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
