# Generated by Django 5.2 on 2025-12-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=20, verbose_name='Statut de validation'),
        ),
    ]
