# Generated by Django 5.2 on 2025-11-30 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondApp', '0002_alter_reinscription_ecole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AddField(
            model_name='membre',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=20, verbose_name='Statut de validation'),
        ),
        migrations.AddField(
            model_name='membre',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AddIndex(
            model_name='membre',
            index=models.Index(fields=['statut'], name='secondApp_m_statut_cabf4f_idx'),
        ),
    ]
