# Generated by Django 5.2 on 2025-11-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondApp', '0002_alter_reinscription_ecole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='reste_a_payer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
