# Generated by Django 5.2 on 2025-11-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondApp', '0003_paiement_reste_a_payer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='reste_a_payer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
