# Generated by Django 5.2 on 2025-11-12 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondApp', '0003_equipedirigeante_typeevenement_evenement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reinscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('numeroUrgence', models.CharField(blank=True, max_length=20, null=True, verbose_name="Numéro d'urgence")),
                ('ecole', models.CharField(blank=True, max_length=50, null=True)),
                ('niveauEtude', models.CharField(blank=True, max_length=20, null=True, verbose_name="Niveau d'étude")),
                ('filiere', models.CharField(blank=True, max_length=150, null=True)),
                ('date_reinscription', models.DateTimeField(auto_now_add=True)),
                ('photo_annuelle', models.ImageField(blank=True, null=True, upload_to='reinscriptions/%Y/', verbose_name="Photo de l'année")),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reinscriptions', to='secondApp.annee')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reinscriptions', to='secondApp.membre')),
            ],
        ),
    ]
