# Generated by Django 5.2 on 2025-12-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondApp', '0003_remove_membre_filiere_membre_date_validation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='filiere',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
