# Generated by Django 5.2 on 2025-12-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondApp', '0004_membre_filiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('refuse', 'Refusé'), ('bloquer', 'Bloquer')], default='en_attente', max_length=20, verbose_name='Statut de validation'),
        ),
    ]
