# Generated by Django 5.2 on 2025-11-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondApp', '0004_alter_paiement_reste_a_payer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(blank=True, choices=[('payé', 'Payé'), ('non_payé', 'Non payé'), ('moitié_payé', 'Moitié payé'), ('avance', 'Avance')], max_length=20, null=True),
        ),
    ]
