# Generated by Django 5.2 on 2025-11-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondApp', '0005_alter_paiement_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='filiere',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
