# Generated by Django 5.2 on 2025-12-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondApp', '0005_alter_membre_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='ajout_par',
            field=models.CharField(default=1, max_length=350),
            preserve_default=False,
        ),
    ]
