# Generated by Django 5.2 on 2025-11-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondApp', '0005_utilisateur_equipedirigeante_utilisateur_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('membreLambda', 'Membre Lambda'), ('membreEquipe', "Membre de l'équipe")], default='membreLambda', max_length=20, verbose_name='Rôle'),
        ),
    ]
