# Generated by Django 5.2 on 2025-12-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondApp', '0006_paiement_ajout_par'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='ajout_par',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
