# Generated by Django 5.2 on 2025-11-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondApp', '0006_alter_utilisateur_options_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='reinscription',
            name='adresse',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
