# Generated by Django 5.2 on 2025-12-16 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondApp', '0007_alter_paiement_ajout_par'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='evenement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secondApp.evenement'),
        ),
    ]
