# Generated by Django 5.2 on 2025-12-18 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondApp', '0008_alter_paiement_evenement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='evenement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='secondApp.evenement'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='membre_Reinscris',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='secondApp.reinscription'),
        ),
    ]
