# Generated by Django 5.2 on 2025-12-28 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondApp', '0009_alter_paiement_evenement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipedirigeante',
            name='annee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipeDirigeante', to='secondApp.annee'),
        ),
    ]
