# Generated by Django 5.2 on 2025-12-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondApp', '0010_equipedirigeante_annee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipedirigeante',
            options={'verbose_name': 'Équipe Dirigeante', 'verbose_name_plural': 'Équipes Dirigeantes'},
        ),
        migrations.AddField(
            model_name='equipedirigeante',
            name='est_publie',
            field=models.BooleanField(default=False, verbose_name='Publié'),
        ),
    ]
