# Generated by Django 5.2 on 2025-12-30 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondApp', '0011_alter_equipedirigeante_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default="Rapport d'évènement", max_length=200, verbose_name='Titre du rapport')),
                ('resume', models.TextField(help_text="Bref résumé de l'évènement et de ses objectifs.", verbose_name='Résumé général')),
                ('objectifs', models.TextField(blank=True, help_text="Objectifs principaux de l'évènement.", null=True, verbose_name='Objectifs')),
                ('deroulement', models.TextField(blank=True, help_text='Décrire les grandes étapes du déroulement.', null=True, verbose_name='Déroulement')),
                ('points_positifs', models.TextField(blank=True, help_text='Ce qui a bien fonctionné.', null=True, verbose_name='Points positifs')),
                ('points_a_ameliorer', models.TextField(blank=True, null=True, verbose_name='Points à améliorer')),
                ('recommandations', models.TextField(blank=True, help_text='Conseils, idées, bonnes pratiques à retenir.', null=True, verbose_name='Recommandations pour les prochains bureaux')),
                ('nb_participants', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de participants')),
                ('budget_prevu', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Budget prévu')),
                ('budget_depense', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Budget dépensé')),
                ('date_rapport', models.DateTimeField(auto_now_add=True, verbose_name='Date de création du rapport')),
                ('derniere_modif', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_evenement', to=settings.AUTH_USER_MODEL, verbose_name='Rédigé par')),
                ('evenement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rapport', to='secondApp.evenement', verbose_name='Évènement')),
            ],
            options={
                'verbose_name': "Rapport d'évènement",
                'verbose_name_plural': "Rapports d'évènements",
                'ordering': ['-date_rapport'],
            },
        ),
    ]
