# Generated by Django 5.2 on 2026-01-01 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondApp', '0012_rapportevenement'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
            ],
        ),
    ]
