# Generated by Django 5.2 on 2026-01-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondApp', '0013_alter_utilisateur_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='mot_de_passe',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='nom_utilisateur',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='toute_info_sur_identite',
            field=models.TextField(blank=True, null=True),
        ),
    ]
