# Generated by Django 5.2 on 2026-01-01 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondApp', '0014_membre_mot_de_passe_membre_nom_utilisateur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='profession',
        ),
    ]
